site_name: minikube-workbench
site_description: minikube-workbench
site_author: "Chris Mendoza"
site_url: https://chris-mendoza.github.io
repo_name: minikube-workbench
repo_url: https://github.com/chris-mendoza/minikube-workbench

# EDIT LINES ABOVE THIS ONE FOR A NEW REPOSITORY
edit_uri: "edit/main/docs/docs/"
docs_dir: docs
site_dir: site
remote_branch: gh-pages

plugins:
  - search
  - awesome-pages
  - macros
  - git-revision-date-localized:
      fallback_to_build_date: true
  - mkdocs-video
  #- tags:
  #    tags_file: general/tags.md

theme:
  name: material
  language: en
  features:
    - search.highlight
    - search.share
    - content.code.annotate
    - navigation.top
    - navigation.indexes
    - content.action.edit
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: light
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: "assets/images/icon.jpg"
  favicon: "assets/images/favicon.ico"
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    admonition:
      quote: material/code-tags

extra_css:
  - stylesheets/extra.css

nav:
  - ...
  - General:
      - Tag Index: general/tags.md
      - Contributing: general/contributing.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - meta
  - footnotes
  # - def_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.tasklist:
      clickable_checkbox: false
      custom_checkbox: true
  - markdown_grid_tables: